// mod print;
// mod vars;
// mod iterate;
// mod ownership;
// mod slices;
// mod structs;
// mod enums;
// mod collections;
// mod erros;
// mod generics;
// mod types;
// mod algo;
// mod traits;
mod lifetimes;
// mod game;
fn main() {
    // print::run();
    // vars::run();
    // ownership::run();
    // enums::run();
    // collections::run();
    // erros::run();
    // traits::run();
    lifetimes::run();
    // game::run();
    //   let nums: [i32; 5]  = [2,4,6,8,10];
    //   algo::sumnumbers(nums);
    // let s =  algo::reversestring("Hello");
    //   println!("{}", s);
}
